# Generated by Django 6.1 on 2026-09-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_nombre_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
    ]
